version: '3.2'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    #volumes:
    #  - $HOME/postgres:/var/lib/postgresql/data
    networks:
      - app

  api:
    environment:
      DATABASE_HOST: db
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "4000:4000"
    depends_on:
      - db
    command:
      - ./run.sh
    networks:
      - app

networks:
  app:
    driver: bridge
